name: Deploy para FTP

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v2

    - name: Instalar cliente FTP
      run: sudo apt-get install -y lftp

    - name: Enviar para FTP
      run: |
        lftp -e "set ftp:ssl-allow no; \
                 open -u $FTP_USERNAME,$FTP_PASSWORD ftp://185.27.134.155; \
                 mirror --reverse --verbose ./ /htdocs; \
                 bye"
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

    - name: Verificar status do deploy
      run: |
        if [ $? -eq 0 ]; then
          echo "Deploy realizado com sucesso!"
        else
          echo "Falha ao realizar o deploy."
          exit 1
        fi
